#!/usr/bin/env bash
#accepts arguments as string
#The '-z' switch will test if the expansion of "$1" is a null string or not
# also u can either use [$# -eq 0]=> if the no. of arguments($#) is 0 then echo message
# else ping IP 5 times

if [ -z "$1" ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
