#!/usr/bin/env bash
# Displays the contents of the file `/etc/passwd`.
# and only displays username,user id and Home directory path for the user

while read passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
