#!/usr/bin/env bash
#host file=>(/etc/hosts) resolves or translates hostnames to ip address
#(f**k chekcer) because docker treats etc/hosts without any regards for modifications
#copies the host file to ~/hosts.new
#then adds the two sites to ~/hosts.new (overwrites the first, appends the second{so the first won't be overwritten})
#then copy the contents of ~/hosts.new to the host file
#resolves the new ip addresses of the hostnames

cp /etc/hosts ~/hosts.new
echo "127.0.0.2 localhost" > ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
